---
- name: Build Docker images from Dockerfiles.
  docker_image:
    name: "{{ item.name }}"
    tag: "{{ item.tag }}"
    path: "/vagrant/provisioning/{{ item.directory }}"
    state: build
  with_items:
    - { name: data, tag: "data", directory: data }
    - { name: www, tag: "flask", directory: www }
    - { name: db, tag: mysql, directory: db }
